# Generated by Django 3.1.4 on 2021-01-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_delete_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
        migrations.RemoveField(
            model_name='job',
            name='vacancies',
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='role',
            field=models.CharField(choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary')], max_length=30, null=True),
        ),
    ]
