# Generated by Django 3.1.4 on 2021-01-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20210110_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jd',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
